Repository bakera/html-book, pull requests merged in 2021-11, with the labels that each got.

#367 3-5：prerenderの記載を入れ替えて少し追記
  md_text/3-5.md
Labels: Chapter3

#368 3-9-2：maxlength/minlengthの見出しを削除
  md_text/3-9-2.md
Labels: Chapter3

#372 maxlengthの微調整
  md_text/3-9.md
Labels: Chapter3

#374 3-9-2/4-2：output要素のa11y周りを整理
  md_text/3-9-2.md
  md_text/4-2.md
Labels: Chapter3, Chapter4

#371 href属性を持たない場合の追記
  md_text/3-5.md
Labels: Chapter3

#365 1-1再構成
  md_text/1-1.md
Labels: Chapter1

#366 1-2再構成
  md_text/1-2.md
Labels: Chapter1

#376 1-1/1-2表現をある程度統一
  md_text/1-1.md
  md_text/1-2.md
Labels: 表現

#377 支援技術の英語表記を複数形→単数形に
  md_text/1-2.md
Labels: 表現, Chapter1

#370 1-3を標準化と歴史の話として再編成してみる
  md_text/1-3.md
Labels: Chapter1

#380 1-5再構成
  md_text/1-5.md
Labels: Chapter1

#378 1-4再構成
  md_text/1-4.md
Labels: Chapter1

#381 1-6再構成
  md_text/1-6.md
Labels: Chapter1

#382 1-7再構成
  md_text/1-7.md
Labels: Chapter1

#328 2-8/3-8：foster parentingの整理
  md_text/2-8.md
  md_text/3-8.md
Labels: Chapter2, Chapter3

#326 Chapter2-4のレビュー反映
  md_text/2-4.md
Labels: Chapter2

#390 2-3-2削除
  md_text/2-3-2.md
Labels: Chapter2

#392 2-2校正
  md_text/2-2.md
Labels: Chapter2

#389 2-1校正/推敲
  md_text/2-1.md
Labels: Chapter2

#397 2-3再構成
  md_text/2-3.md
Labels: Chapter2

#394 2-5校正
  md_text/2-5.md
Labels: Chapter2

#395 2-6校正
  md_text/2-6.md
Labels: Chapter2

#317 3-5：ping属性の追記
  md_text/3-5.md
Labels: Chapter3

#398 2-8校正
  md_text/2-8.md
Labels: Chapter2

#396 2-7校正
  md_text/2-7.md
Labels: Chapter2

#399 2-6/2-8：誤字・コード例調整
  md_text/2-6.md
  md_text/2-8.md
Labels: Chapter2

#341 3-2：section要素のコード例を拡充
  md_text/3-2.md
Labels: Chapter3

#401 3-2：アウトラインの説明の調整
  md_text/3-2.md
Labels: Chapter2

#400 3-2から4-2への参照を追加
  md_text/3-2.md
Labels: Chapter3
