Repository bakera/html-book, pull requests merged in 2021-12, with the labels that each got.

#404 a11y/内容モデルのコメントを見出しに
  md_text/3-10.md
  md_text/3-11.md
  md_text/3-2.md
  md_text/3-3.md
  md_text/3-4.md
  md_text/3-5.md
  md_text/3-6.md
  md_text/3-7.md
  md_text/3-8.md
  md_text/3-9-2.md
  md_text/3-9.md
  md_text/4-1.md
Labels: Chapter3

#373 3-4：data要素のコラム化
  md_text/3-4.md
Labels: Chapter3

#391 2-4の順番変更、全体調整
  md_text/2-4.md
Labels: Chapter2

#410 dl要素の注意点を追記
  md_text/3-3.md
Labels: Chapter3

#411 2-5～2-8追加表現調整
  md_text/2-5.md
  md_text/2-6.md
  md_text/2-7.md
  md_text/2-8.md
Labels: Chapter2

#414 3-7: embed要素をコラムとして復帰
  md_text/3-7.md
Labels: Chapter3

#408 3-1校正
  md_text/3-1.md
Labels: Chapter3

#428 3-2：セクショニングルートのスクリーンリーダーの扱い
  md_text/3-2.md
Labels: Chapter3

#429 hgroup追加案
  md_text/3-2.md
Labels: Chapter3

#433 dt/dd要素の内容モデルの追記
  md_text/3-3.md
Labels: Chapter3

#406 ４章の JavaScript コードを見直す
  md_text/4-1.md
  md_text/4-2.md
  md_text/4-4.md
Labels: Chapter4

#412 3-3校正
  md_text/3-3.md
Labels: Chapter3

#436 3-5：見出しの組み替え
  md_text/3-5.md
Labels: Chapter3

#415 3-6校正
  md_text/3-6.md
Labels: Chapter3

#439 3-6：cite属性/datetime属性の作成
  md_text/3-6.md
Labels: Chapter3

#413 3-4校正
  md_text/3-4.md
Labels: Chapter3

#420 3-8校正/内容調整
  md_text/3-8.md
Labels: Chapter3

#409 3-5内容調整
  md_text/3-5.md
Labels: Chapter3

#417 3-7校正/内容調整
  md_text/3-7.md
Labels: Chapter3

#421 3-9校正/内容調整
  md_text/3-9.md
Labels: Chapter3

#422 3-9-2校正/内容調整
  md_text/3-9-2.md
Labels: Chapter3

#423 3-10校正/内容調整
  md_text/3-10.md
Labels: Chapter3

#424 3-11の校正/内容調整
  md_text/3-11.md
Labels: Chapter3
